version: "3.9"

services:
  laravel:
    container_name: hands-on-laravel
    image: php:8.1-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/var/www
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: